# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
contentDir = 'content/english'
title = "Burak Sina Akbudak en"
weight = 10

[tr]
languageName = "Turkish"
contentDir = 'content/turkish'
languagedirection = "ltr"
title = "Burak Sina Akbudak tr"
weight = 20
