# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

# [[main]]
# identifier = "about"
# name = "About Me"
# url = "/"

# [main.params]
# icon = "user"
# newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Fansesi"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "Linkedin"
url = "https://www.linkedin.com/in/burak-sina-akbudak-2407a227b/"

[social.params]
icon = "brand-linkedin"

[[social]]
identifier = "youtube"
name = "YouTube"
url = "https://www.youtube.com/@buraksinaakbudak"

[social.params]
icon = "brand-youtube"

[[social]]
identifier = "instagram"
name = "Instagram"
url = "https://www.instagram.com/sina.akbdk/"

[social.params]
icon = "brand-instagram"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:buraksinaakbudak@gmail.com"

[social.params]
icon = "mail"

